#发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
rocketmq:
  producerGroup: ProducerGroupName
  #mq的nameserver地址
  namesrvAddr: 10.58.22.190:9876;10.58.166.150:9876;10.112.169.100:9876;10.112.169.101:9876
  #员工相关topic
  staffTopic: HrStaff